spring.application.name=sportify-backend
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/sportify_bd
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=none
=======

# Configuración de la conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nombre_bd
spring.datasource.username=postgres
#contraseña de cada uno
spring.datasource.password=123456
 

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
>>>>>>> ad6903e743ef7d62da8fa2cfd7c56664d611d4c4
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect