spring.application.name=sportify-backend

# Configuración de la conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Sportify_bd
spring.datasource.username=postgres
#contraseña de cada uno
spring.datasource.password=123456

spring.datasource.password=leonardo26
 
# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
